### Get basic page
GET http://192.168.30.6

### Get api status
GET http://192.168.30.6/api/status
Authorization: Basic user:pass

### api - set status
POST http://192.168.30.6/api/status
Content-Type: application/json
Authorization: Basic user:pass

[
  {
    "Relay": 1,
    "Name": "Pump",
    "State": 1
  },
  {
    "Relay": 2,
    "Name": "UV Light",
    "State": 0
  },
  {
    "Relay": 3,
    "Name": "Skimmer",
    "State": 1
  }
]


### api - toggle
POST http://192.168.30.6/api/toggle/RELAY1
Authorization: Basic user:pass

### api - enable
POST http://192.168.30.6/api/enable/RELAY3
Authorization: Basic user:pass

### api - disable
POST http://192.168.30.6/api/disable/RELAY1
Authorization: Basic dXNlcjpwYXNz